// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const SandboxItems = sequelize.define('sandboxItems', {
    untitledId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
    },
    singleDocumentPath: {
      type: DataTypes.STRING,
    },
    multipleDocumentsPath: {
      type: DataTypes.ARRAY(DataTypes.STRING),
    },
    locationBis: {
      type: DataTypes.STRING,
    },
    jsonText: {
      type: DataTypes.STRING,
    },
    jsonFile: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'sandbox_items',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  SandboxItems.associate = (models) => {
  };

  return SandboxItems;
};
